fix: release system

diff --git a/.github/workflows/ci-main.yml b/.github/workflows/ci-main.yml
--- a/.github/workflows/ci-main.yml
+++ b/.github/workflows/ci-main.yml
@@ -62,7 +62,7 @@ jobs:
         version:
           - 11
           # - 16
-          # - 17  
+          # - 17
         distribution:
           - temurin
           - zulu
@@ -99,6 +99,20 @@ jobs:
         run: |
           ./src/test/resources/run-s3-tests.sh
 
+  publish:
+    runs-on: ubuntu-latest
+    needs: [runTests, meta]
+    steps:
+      - uses: actions/checkout@v2
+      - uses: actions/setup-java@v3.9.0
+        with:
+          distribution: zulu
+          java-version: 11
+          cache: "maven"
+      - name: Maven Set version
+        run: |
+          mvn versions:set -DnewVersion=${{ needs.meta.outputs.new_release_version }}
+
       #Store the target
       - uses: actions/upload-artifact@v3
         with:
@@ -108,88 +122,95 @@ jobs:
         with:
           name: pom
           path: pom.xml
-
-  Containerize:
-    runs-on: ubuntu-latest
-    needs: [runTests, meta]
-    steps:
-      #Yes we need code
-      - uses: actions/checkout@v2
-      - uses: actions/download-artifact@v3
-        with:
-          name: s3proxy
-          path: target
-      - uses: actions/download-artifact@v3
-        with:
-          name: pom
-          path: .
-      # These steps are quick and will work or if fail only because of external issues
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v2
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
-
-      - name: Login to DockerHub
-        uses: docker/login-action@v2.1.0
-        if: github.event_name != 'pull_request' && needs.meta.outputs.dockerhub-publish == 'true'
-        with:
-          username: ${{ secrets.DOCKER_USER }}
-          password: ${{ secrets.DOCKER_PASS }}
-
-      - name: Login to DockerHub
-        uses: docker/login-action@v2.1.0
-        if: github.event_name != 'pull_request'
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-
-      #Generate Meta
-      - name: Build and push
-        uses: docker/build-push-action@v3
-        with:
-          context: .
-          platforms: linux/amd64,linux/arm64
-          push: ${{ github.event_name != 'pull_request' }}
-          tags: ${{ needs.meta.outputs.container_base }}
-          labels: ${{ needs.meta.outputs.container_labels }}
-          build-args: |
-            BUILDTIME=${{ needs.meta.outputs.container_buildtime }}
-            VERSION=${{ needs.meta.outputs.container_version }}
-            REVISION=${{ needs.meta.outputs.container_revision }}
-          cache-from: type=registry,ref=${{ needs.meta.outputs.container_base }}
-          cache-to: type=inline
-      - uses: actions/setup-node@v3
-        with:
-          node-version: "14"
-      - name: Setup regctl
-        if: github.event_name != 'pull_request' && needs.meta.outputs.dockerhub-publish == 'true'
-        run: |
-          curl -L https://github.com/regclient/regclient/releases/download/v0.3.5/regctl-linux-amd64 >/tmp/regctl
-          chmod 755 /tmp/regctl
-
-      - name: Docker meta
-        if: github.event_name != 'pull_request' && needs.meta.outputs.dockerhub-publish == 'true'
-        id: docker_action_meta
-        uses: docker/metadata-action@v4.3.0
-        with:
-          images: andrewgaul/s3proxy
-          flavor: |
-            latest=false
-          tags: |
-            type=sha
-            type=semver,pattern={{version}},value=${{ needs.meta.outputs.new_release_version }}
-            type=semver,pattern={{major}},value=${{ needs.meta.outputs.new_release_version }}
-            type=semver,pattern={{major}}.{{minor}},value=${{ needs.meta.outputs.new_release_version }}
-            type=ref,event=branch
-            type=ref,event=pr
-            type=ref,event=tag
-          labels: |
-            org.opencontainers.image.licenses=Apache-2.0
-      - name: Publish to Docker
-        if: github.event_name != 'pull_request' && needs.meta.outputs.dockerhub-publish == 'true'
-        run: |
-          for line in $CONTAINER_DEST_TAGS; do echo working on "$line"; /tmp/regctl image copy $SOURCE_CONTAINER $line; done
+      - name: Deploy to Github Package Registry
         env:
-          SOURCE_CONTAINER: ${{ needs.meta.outputs.new_release_version }}
-          CONTAINER_DEST_TAGS: ${{ steps.docker_action_meta.outputs.tags }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          mkdir ~/.m2
+          echo "<settings><servers><server><id>github</id><username>OWNER</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
+          mvn deploy
+
+  # Containerize:
+  #   runs-on: ubuntu-latest
+  #   needs: [runTests, meta]
+  #   steps:
+  #     #Yes we need code
+  #     - uses: actions/checkout@v2
+  #     - uses: actions/download-artifact@v3
+  #       with:
+  #         name: s3proxy
+  #         path: target
+  #     - uses: actions/download-artifact@v3
+  #       with:
+  #         name: pom
+  #         path: .
+  #     # These steps are quick and will work or if fail only because of external issues
+  #     - name: Set up QEMU
+  #       uses: docker/setup-qemu-action@v2
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v2
+
+  #     - name: Login to DockerHub
+  #       uses: docker/login-action@v2.1.0
+  #       if: github.event_name != 'pull_request' && needs.meta.outputs.dockerhub-publish == 'true'
+  #       with:
+  #         username: ${{ secrets.DOCKER_USER }}
+  #         password: ${{ secrets.DOCKER_PASS }}
+
+  #     - name: Login to DockerHub
+  #       uses: docker/login-action@v2.1.0
+  #       if: github.event_name != 'pull_request'
+  #       with:
+  #         registry: ghcr.io
+  #         username: ${{ github.actor }}
+  #         password: ${{ secrets.GITHUB_TOKEN }}
+
+  #     #Generate Meta
+  #     - name: Build and push
+  #       uses: docker/build-push-action@v3
+  #       with:
+  #         context: .
+  #         platforms: linux/amd64,linux/arm64
+  #         push: ${{ github.event_name != 'pull_request' }}
+  #         tags: ${{ needs.meta.outputs.container_base }}
+  #         labels: ${{ needs.meta.outputs.container_labels }}
+  #         build-args: |
+  #           BUILDTIME=${{ needs.meta.outputs.container_buildtime }}
+  #           VERSION=${{ needs.meta.outputs.container_version }}
+  #           REVISION=${{ needs.meta.outputs.container_revision }}
+  #         cache-from: type=registry,ref=${{ needs.meta.outputs.container_base }}
+  #         cache-to: type=inline
+  #     - uses: actions/setup-node@v3
+  #       with:
+  #         node-version: "14"
+  #     - name: Setup regctl
+  #       if: github.event_name != 'pull_request' && needs.meta.outputs.dockerhub-publish == 'true'
+  #       run: |
+  #         curl -L https://github.com/regclient/regclient/releases/download/v0.3.5/regctl-linux-amd64 >/tmp/regctl
+  #         chmod 755 /tmp/regctl
+
+  #     - name: Docker meta
+  #       if: github.event_name != 'pull_request' && needs.meta.outputs.dockerhub-publish == 'true'
+  #       id: docker_action_meta
+  #       uses: docker/metadata-action@v4.3.0
+  #       with:
+  #         images: andrewgaul/s3proxy
+  #         flavor: |
+  #           latest=false
+  #         tags: |
+  #           type=sha
+  #           type=semver,pattern={{version}},value=${{ needs.meta.outputs.new_release_version }}
+  #           type=semver,pattern={{major}},value=${{ needs.meta.outputs.new_release_version }}
+  #           type=semver,pattern={{major}}.{{minor}},value=${{ needs.meta.outputs.new_release_version }}
+  #           type=ref,event=branch
+  #           type=ref,event=pr
+  #           type=ref,event=tag
+  #         labels: |
+  #           org.opencontainers.image.licenses=Apache-2.0
+  #     - name: Publish to Docker
+  #       if: github.event_name != 'pull_request' && needs.meta.outputs.dockerhub-publish == 'true'
+  #       run: |
+  #         for line in $CONTAINER_DEST_TAGS; do echo working on "$line"; /tmp/regctl image copy $SOURCE_CONTAINER $line; done
+  #       env:
+  #         SOURCE_CONTAINER: ${{ needs.meta.outputs.new_release_version }}
+  #         CONTAINER_DEST_TAGS: ${{ steps.docker_action_meta.outputs.tags }}
